name: hotkey_manager_example
description: Demonstrates how to use the hotkey_manager plugin.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  bot_toast: ^4.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hotkey_manager:
    path: ../
  preference_list: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
