name: hotkey_manager_example
description: Demonstrates how to use the hotkey_manager plugin.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hotkey_manager:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  uses-material-design: true
