name: hotkey_manager
description: This plugin allows Flutter desktop apps to defines system/inapp wide hotkey (i.e. shortcut).
version: 0.2.3
homepage: https://github.com/leanflutter/hotkey_manager

platforms:
  linux:
  macos:
  windows:

topics:
  - hotkey
  - shortcuts
  - global-hotkey
  - global-shortcuts

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  hotkey_manager_linux: ^0.2.0
  hotkey_manager_macos: ^0.2.0
  hotkey_manager_platform_interface: ^0.2.0
  hotkey_manager_windows: ^0.2.0
  uuid: '>=3.0.7 <5.0.0'

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2

flutter:
  plugin:
    platforms:
      linux:
        default_package: hotkey_manager_linux
      macos:
        default_package: hotkey_manager_macos
      windows:
        default_package: hotkey_manager_windows
